version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    extra_hosts:
      - "dockerlab:host-gateway"
    volumes:
      - /mnt/nas1/docker/prometheus/config:/etc/prometheus
      - /mnt/nas1/docker/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /mnt/nas1/docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - /mnt/nas1/docker/grafana/data:/var/lib/grafana

  influxdb:
    image: influxdb:2.7.6-alpine
    container_name: influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
    extra_hosts:
      - "dockerlab:host-gateway"
    volumes:
      - /mnt/nas1/docker/influxdb2/data:/var/lib/influxdb2
      - /mnt/nas1/docker/influxdb2/config:/etc/influxdb2
      - /mnt/nas1/docker/influxdb2/scripts:/docker-entrypoint-initdb.d

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    pid: "host"
    restart: always
    entrypoint: /bin/bash -c "/entrypoint.sh telegraf"
    extra_hosts:
      - "dockerlab:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nas1/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs