# Currently untested as written
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 32400:32400
    devices:
     - /dev/dri:/dev/dri # QuickSync
    volumes:
      - /mnt/nas1/docker/media/plex/plex/config:/config
      - /mnt/nas1/media:/media
      - /mnt/nas1/downloads:/downloads
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/nas1/docker/media/plex/overseer/config:/config
      - /mnt/nas1/media:/media
      - /mnt/nas1/downloads:/downloads
    ports:
      - 5055:5055
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/nas1/docker/media/plex/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
