export interface Language {
  name: string;
  value: string;
}

export const DATE_RANGES = [
  { label: 'Today', value: 'daily' },
  { label: 'This week', value: 'weekly' },
  { label: 'This month', value: 'monthly' },
] as const;

export type DateRange = (typeof DATE_RANGES)[number]['value'];

// Popular languages extracted from GitHub trending and the API
export const POPULAR_LANGUAGES: Language[] = [
  { name: 'Any Language', value: 'all' },
  { name: 'JavaScript', value: 'javascript' },
  { name: 'TypeScript', value: 'typescript' },
  { name: 'Python', value: 'python' },
  { name: 'Java', value: 'java' },
  { name: 'C++', value: 'c++' },
  { name: 'C#', value: 'c#' },
  { name: 'PHP', value: 'php' },
  { name: 'C', value: 'c' },
  { name: 'Go', value: 'go' },
  { name: 'Rust', value: 'rust' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'Swift', value: 'swift' },
  { name: 'Kotlin', value: 'kotlin' },
  { name: 'Dart', value: 'dart' },
  { name: 'Scala', value: 'scala' },
  { name: 'R', value: 'r' },
  { name: 'Shell', value: 'shell' },
  { name: 'PowerShell', value: 'powershell' },
  { name: 'HTML', value: 'html' },
  { name: 'CSS', value: 'css' },
  { name: 'SCSS', value: 'scss' },
  { name: 'Vue', value: 'vue' },
  { name: 'Jupyter Notebook', value: 'jupyter-notebook' },
  { name: 'Dockerfile', value: 'dockerfile' },
  { name: 'YAML', value: 'yaml' },
  { name: 'JSON', value: 'json' },
  { name: 'Markdown', value: 'markdown' },
];

// All available languages from the API (top 100 most common)
export const ALL_LANGUAGES: Language[] = [
  { name: 'Any Language', value: 'all' },
  { name: '1C Enterprise', value: '1c-enterprise' },
  { name: 'ABAP', value: 'abap' },
  { name: 'ActionScript', value: 'actionscript' },
  { name: 'Ada', value: 'ada' },
  { name: 'Agda', value: 'agda' },
  { name: 'AGS Script', value: 'ags-script' },
  { name: 'Alloy', value: 'alloy' },
  { name: 'AMPL', value: 'ampl' },
  { name: 'ANTLR', value: 'antlr' },
  { name: 'ApacheConf', value: 'apacheconf' },
  { name: 'Apex', value: 'apex' },
  { name: 'API Blueprint', value: 'api-blueprint' },
  { name: 'APL', value: 'apl' },
  { name: 'AppleScript', value: 'applescript' },
  { name: 'Arc', value: 'arc' },
  { name: 'AsciiDoc', value: 'asciidoc' },
  { name: 'ASN.1', value: 'asn.1' },
  { name: 'Classic ASP', value: 'classic-asp' },
  { name: 'ASP.NET', value: 'asp.net' },
  { name: 'Assembly', value: 'assembly' },
  { name: 'Astro', value: 'astro' },
  { name: 'ATS', value: 'ats' },
  { name: 'Augeas', value: 'augeas' },
  { name: 'AutoHotkey', value: 'autohotkey' },
  { name: 'AutoIt', value: 'autoit' },
  { name: 'Awk', value: 'awk' },
  { name: 'Ballerina', value: 'ballerina' },
  { name: 'BASIC', value: 'basic' },
  { name: 'Batchfile', value: 'batchfile' },
  { name: 'Befunge', value: 'befunge' },
  { name: 'BibTeX', value: 'bibtex' },
  { name: 'Bicep', value: 'bicep' },
  { name: 'Bison', value: 'bison' },
  { name: 'BitBake', value: 'bitbake' },
  { name: 'Blade', value: 'blade' },
  { name: 'BlitzBasic', value: 'blitzbasic' },
  { name: 'BlitzMax', value: 'blitzmax' },
  { name: 'Bluespec', value: 'bluespec' },
  { name: 'Boo', value: 'boo' },
  { name: 'Boogie', value: 'boogie' },
  { name: 'BQN', value: 'bqn' },
  { name: 'Brainfuck', value: 'brainfuck' },
  { name: 'Brightscript', value: 'brightscript' },
  { name: 'Browserslist', value: 'browserslist' },
  { name: 'C', value: 'c' },
  { name: 'C#', value: 'c#' },
  { name: 'C++', value: 'c++' },
  { name: 'C2hs Haskell', value: 'c2hs-haskell' },
  { name: 'Cabal Config', value: 'cabal-config' },
  { name: 'Caddyfile', value: 'caddyfile' },
  { name: 'Cadence', value: 'cadence' },
  { name: 'Cairo', value: 'cairo' },
  { name: 'CameLIGO', value: 'cameligo' },
  { name: "Cap'n Proto", value: "cap'n-proto" },
  { name: 'CartoCSS', value: 'cartocss' },
  { name: 'Ceylon', value: 'ceylon' },
  { name: 'Chapel', value: 'chapel' },
  { name: 'Charity', value: 'charity' },
  { name: 'ChucK', value: 'chuck' },
  { name: 'Cirru', value: 'cirru' },
  { name: 'Clarion', value: 'clarion' },
  { name: 'Clarity', value: 'clarity' },
  { name: 'Clean', value: 'clean' },
  { name: 'Click', value: 'click' },
  { name: 'CLIPS', value: 'clips' },
  { name: 'Clojure', value: 'clojure' },
  { name: 'Closure Templates', value: 'closure-templates' },
  { name: 'CMake', value: 'cmake' },
  { name: 'COBOL', value: 'cobol' },
  { name: 'CodeQL', value: 'codeql' },
  { name: 'CoffeeScript', value: 'coffeescript' },
  { name: 'ColdFusion', value: 'coldfusion' },
  { name: 'Common Lisp', value: 'common-lisp' },
  { name: 'Cool', value: 'cool' },
  { name: 'Coq', value: 'coq' },
  { name: 'Crystal', value: 'crystal' },
  { name: 'CSON', value: 'cson' },
  { name: 'CSS', value: 'css' },
  { name: 'CSV', value: 'csv' },
  { name: 'Cuda', value: 'cuda' },
  { name: 'CUE', value: 'cue' },
  { name: 'Curry', value: 'curry' },
  { name: 'CWeb', value: 'cweb' },
  { name: 'Cycript', value: 'cycript' },
  { name: 'Cython', value: 'cython' },
  { name: 'D', value: 'd' },
  { name: 'Dafny', value: 'dafny' },
  { name: 'Dart', value: 'dart' },
  { name: 'DataWeave', value: 'dataweave' },
  { name: 'Dhall', value: 'dhall' },
  { name: 'Diff', value: 'diff' },
  { name: 'DIGITAL Command Language', value: 'digital-command-language' },
  { name: 'DM', value: 'dm' },
  { name: 'Dockerfile', value: 'dockerfile' },
  { name: 'Dogescript', value: 'dogescript' },
  { name: 'DTrace', value: 'dtrace' },
  { name: 'Dylan', value: 'dylan' },
  { name: 'E', value: 'e' },
  { name: 'Eagle', value: 'eagle' },
  { name: 'Earthly', value: 'earthly' },
  { name: 'Easybuild', value: 'easybuild' },
  { name: 'EBNF', value: 'ebnf' },
  { name: 'eC', value: 'ec' },
  { name: 'Ecmarkup', value: 'ecmarkup' },
  { name: 'EdgeQL', value: 'edgeql' },
  { name: 'EditorConfig', value: 'editorconfig' },
  { name: 'Eiffel', value: 'eiffel' },
  { name: 'EJS', value: 'ejs' },
  { name: 'Elixir', value: 'elixir' },
  { name: 'Elm', value: 'elm' },
  { name: 'Emacs Lisp', value: 'emacs-lisp' },
  { name: 'EmberScript', value: 'emberscript' },
  { name: 'EQ', value: 'eq' },
  { name: 'Erlang', value: 'erlang' },
  { name: 'Euphoria', value: 'euphoria' },
  { name: 'F#', value: 'f#' },
  { name: 'F*', value: 'f*' },
  { name: 'Factor', value: 'factor' },
  { name: 'Fancy', value: 'fancy' },
  { name: 'Fantom', value: 'fantom' },
  { name: 'Faust', value: 'faust' },
  { name: 'Fennel', value: 'fennel' },
  { name: 'FIGlet Font', value: 'figlet-font' },
  { name: 'Filterscript', value: 'filterscript' },
  { name: 'fish', value: 'fish' },
  { name: 'Fluent', value: 'fluent' },
  { name: 'FLUX', value: 'flux' },
  { name: 'Forth', value: 'forth' },
  { name: 'Fortran', value: 'fortran' },
  { name: 'FreeBasic', value: 'freebasic' },
  { name: 'FreeMarker', value: 'freemarker' },
  { name: 'Frege', value: 'frege' },
  { name: 'Futhark', value: 'futhark' },
  { name: 'G-code', value: 'g-code' },
  { name: 'Game Maker Language', value: 'game-maker-language' },
  { name: 'GAML', value: 'gaml' },
  { name: 'GAMS', value: 'gams' },
  { name: 'GAP', value: 'gap' },
  { name: 'GDScript', value: 'gdscript' },
  { name: 'Gemini', value: 'gemini' },
  { name: 'Genie', value: 'genie' },
  { name: 'Genshi', value: 'genshi' },
  { name: 'Gentoo Ebuild', value: 'gentoo-ebuild' },
  { name: 'Gentoo Eclass', value: 'gentoo-eclass' },
  { name: 'Gerber Image', value: 'gerber-image' },
  { name: 'Gherkin', value: 'gherkin' },
  { name: 'Git Attributes', value: 'git-attributes' },
  { name: 'Git Config', value: 'git-config' },
  { name: 'Gleam', value: 'gleam' },
  { name: 'Glimmer JS', value: 'glimmer-js' },
  { name: 'Glimmer TS', value: 'glimmer-ts' },
  { name: 'GLSL', value: 'glsl' },
  { name: 'Glyph', value: 'glyph' },
  { name: 'GN', value: 'gn' },
  { name: 'Gnuplot', value: 'gnuplot' },
  { name: 'Go', value: 'go' },
  { name: 'Golo', value: 'golo' },
  { name: 'Gosu', value: 'gosu' },
  { name: 'Grace', value: 'grace' },
  { name: 'Gradle', value: 'gradle' },
  { name: 'Gradle Kotlin DSL', value: 'gradle-kotlin-dsl' },
  { name: 'Grammatical Framework', value: 'grammatical-framework' },
  { name: 'Graph Modeling Language', value: 'graph-modeling-language' },
  { name: 'GraphQL', value: 'graphql' },
  { name: 'Graphviz (DOT)', value: 'graphviz-(dot)' },
  { name: 'Groovy', value: 'groovy' },
  { name: 'GSC', value: 'gsc' },
  { name: 'Hack', value: 'hack' },
  { name: 'Haml', value: 'haml' },
  { name: 'Handlebars', value: 'handlebars' },
  { name: 'HAProxy', value: 'haproxy' },
  { name: 'Harbour', value: 'harbour' },
  { name: 'Haskell', value: 'haskell' },
  { name: 'Haxe', value: 'haxe' },
  { name: 'HCL', value: 'hcl' },
  { name: 'HiveQL', value: 'hiveql' },
  { name: 'HLSL', value: 'hlsl' },
  { name: 'HOCON', value: 'hocon' },
  { name: 'HolyC', value: 'holyc' },
  { name: 'hoon', value: 'hoon' },
  { name: 'HTML', value: 'html' },
  { name: 'HTML+ECR', value: 'html+ecr' },
  { name: 'HTML+EEX', value: 'html+eex' },
  { name: 'HTML+ERB', value: 'html+erb' },
  { name: 'HTML+PHP', value: 'html+php' },
  { name: 'HTML+Razor', value: 'html+razor' },
  { name: 'HTTP', value: 'http' },
  { name: 'HXML', value: 'hxml' },
  { name: 'Hy', value: 'hy' },
  { name: 'HyPhy', value: 'hyphy' },
  { name: 'IDL', value: 'idl' },
  { name: 'Idris', value: 'idris' },
  { name: 'IGOR Pro', value: 'igor-pro' },
  { name: 'ImageJ Macro', value: 'imagej-macro' },
  { name: 'Imba', value: 'imba' },
  { name: 'Inform 7', value: 'inform-7' },
  { name: 'INI', value: 'ini' },
  { name: 'Ink', value: 'ink' },
  { name: 'Inno Setup', value: 'inno-setup' },
  { name: 'Io', value: 'io' },
  { name: 'Ioke', value: 'ioke' },
  { name: 'IRC log', value: 'irc-log' },
  { name: 'Isabelle', value: 'isabelle' },
  { name: 'J', value: 'j' },
  { name: 'Janet', value: 'janet' },
  { name: 'JAR Manifest', value: 'jar-manifest' },
  { name: 'Jasmin', value: 'jasmin' },
  { name: 'Java', value: 'java' },
  { name: 'Java Properties', value: 'java-properties' },
  { name: 'Java Server Pages', value: 'java-server-pages' },
  { name: 'JavaScript', value: 'javascript' },
  { name: 'JavaScript+ERB', value: 'javascript+erb' },
  { name: 'JCL', value: 'jcl' },
  { name: 'JFlex', value: 'jflex' },
  { name: 'Jinja', value: 'jinja' },
  { name: 'Jison', value: 'jison' },
  { name: 'Jison Lex', value: 'jison-lex' },
  { name: 'Jolie', value: 'jolie' },
  { name: 'jq', value: 'jq' },
  { name: 'JSON', value: 'json' },
  { name: 'JSON with Comments', value: 'json-with-comments' },
  { name: 'JSON5', value: 'json5' },
  { name: 'JSONiq', value: 'jsoniq' },
  { name: 'JSONLD', value: 'jsonld' },
  { name: 'Jsonnet', value: 'jsonnet' },
  { name: 'Julia', value: 'julia' },
  { name: 'Jupyter Notebook', value: 'jupyter-notebook' },
  { name: 'Just', value: 'just' },
  { name: 'Kaitai Struct', value: 'kaitai-struct' },
  { name: 'KakouneScript', value: 'kakounescript' },
  { name: 'KerboScript', value: 'kerboscript' },
  { name: 'KiCad Layout', value: 'kicad-layout' },
  { name: 'KiCad Legacy Layout', value: 'kicad-legacy-layout' },
  { name: 'KiCad Schematic', value: 'kicad-schematic' },
  { name: 'Kit', value: 'kit' },
  { name: 'Kotlin', value: 'kotlin' },
  { name: 'KRL', value: 'krl' },
  { name: 'Kusto', value: 'kusto' },
  { name: 'kvlang', value: 'kvlang' },
  { name: 'LabVIEW', value: 'labview' },
  { name: 'Lark', value: 'lark' },
  { name: 'Lasso', value: 'lasso' },
  { name: 'Latte', value: 'latte' },
  { name: 'Lean', value: 'lean' },
  { name: 'Less', value: 'less' },
  { name: 'Lex', value: 'lex' },
  { name: 'LFE', value: 'lfe' },
  { name: 'LigoLANG', value: 'ligolang' },
  { name: 'LilyPond', value: 'lilypond' },
  { name: 'Limbo', value: 'limbo' },
  { name: 'Linker Script', value: 'linker-script' },
  { name: 'Linux Kernel Module', value: 'linux-kernel-module' },
  { name: 'Liquid', value: 'liquid' },
  { name: 'Literate Agda', value: 'literate-agda' },
  { name: 'Literate CoffeeScript', value: 'literate-coffeescript' },
  { name: 'Literate Haskell', value: 'literate-haskell' },
  { name: 'LiveScript', value: 'livescript' },
  { name: 'LLVM', value: 'llvm' },
  { name: 'Logos', value: 'logos' },
  { name: 'Logtalk', value: 'logtalk' },
  { name: 'LOLCODE', value: 'lolcode' },
  { name: 'LookML', value: 'lookml' },
  { name: 'LoomScript', value: 'loomscript' },
  { name: 'LSL', value: 'lsl' },
  { name: 'LTspice Symbol', value: 'ltspice-symbol' },
  { name: 'Lua', value: 'lua' },
  { name: 'Luau', value: 'luau' },
  { name: 'M', value: 'm' },
  { name: 'M4', value: 'm4' },
  { name: 'M4Sugar', value: 'm4sugar' },
  { name: 'Macaulay2', value: 'macaulay2' },
  { name: 'Makefile', value: 'makefile' },
  { name: 'Mako', value: 'mako' },
  { name: 'Markdown', value: 'markdown' },
  { name: 'Marko', value: 'marko' },
  { name: 'Mask', value: 'mask' },
  { name: 'Mathematica', value: 'mathematica' },
  { name: 'MATLAB', value: 'matlab' },
  { name: 'Maven POM', value: 'maven-pom' },
  { name: 'Max', value: 'max' },
  { name: 'MAXScript', value: 'maxscript' },
  { name: 'mcfunction', value: 'mcfunction' },
  { name: 'MDX', value: 'mdx' },
  { name: 'Mercury', value: 'mercury' },
  { name: 'Mermaid', value: 'mermaid' },
  { name: 'Meson', value: 'meson' },
  { name: 'Metal', value: 'metal' },
  { name: 'MiniD', value: 'minid' },
  { name: 'Mint', value: 'mint' },
  { name: 'mIRC Script', value: 'mirc-script' },
  { name: 'MLIR', value: 'mlir' },
  { name: 'Modelica', value: 'modelica' },
  { name: 'Modula-2', value: 'modula-2' },
  { name: 'Modula-3', value: 'modula-3' },
  { name: 'Module Management System', value: 'module-management-system' },
  { name: 'Mojo', value: 'mojo' },
  { name: 'Monkey', value: 'monkey' },
  { name: 'Moocode', value: 'moocode' },
  { name: 'MoonScript', value: 'moonscript' },
  { name: 'Motoko', value: 'motoko' },
  { name: 'Motorola 68K Assembly', value: 'motorola-68k-assembly' },
  { name: 'Move', value: 'move' },
  { name: 'MQL4', value: 'mql4' },
  { name: 'MQL5', value: 'mql5' },
  { name: 'MTML', value: 'mtml' },
  { name: 'MUF', value: 'muf' },
  { name: 'mupad', value: 'mupad' },
  { name: 'Muse', value: 'muse' },
  { name: 'Mustache', value: 'mustache' },
  { name: 'Myghty', value: 'myghty' },
  { name: 'nanorc', value: 'nanorc' },
  { name: 'NASL', value: 'nasl' },
  { name: 'Nasal', value: 'nasal' },
  { name: 'NCL', value: 'ncl' },
  { name: 'Nearley', value: 'nearley' },
  { name: 'Nemerle', value: 'nemerle' },
  { name: 'NEON', value: 'neon' },
  { name: 'nesC', value: 'nesc' },
  { name: 'NetLinx', value: 'netlinx' },
  { name: 'NetLinx+ERB', value: 'netlinx+erb' },
  { name: 'NetLogo', value: 'netlogo' },
  { name: 'NewLisp', value: 'newlisp' },
  { name: 'Nextflow', value: 'nextflow' },
  { name: 'Nginx', value: 'nginx' },
  { name: 'Nim', value: 'nim' },
  { name: 'Ninja', value: 'ninja' },
  { name: 'Nit', value: 'nit' },
  { name: 'Nix', value: 'nix' },
  { name: 'NL', value: 'nl' },
  { name: 'NMODL', value: 'nmodl' },
  { name: 'NPM Config', value: 'npm-config' },
  { name: 'NSIS', value: 'nsis' },
  { name: 'Nu', value: 'nu' },
  { name: 'NumPy', value: 'numpy' },
  { name: 'Nunjucks', value: 'nunjucks' },
  { name: 'Nushell', value: 'nushell' },
  { name: 'NWScript', value: 'nwscript' },
  { name: 'OASv2-json', value: 'oasv2-json' },
  { name: 'OASv2-yaml', value: 'oasv2-yaml' },
  { name: 'OASv3-json', value: 'oasv3-json' },
  { name: 'OASv3-yaml', value: 'oasv3-yaml' },
  { name: 'Oberon', value: 'oberon' },
  { name: 'ObjDump', value: 'objdump' },
  {
    name: 'Object Data Instance Notation',
    value: 'object-data-instance-notation',
  },
  { name: 'Objective-C', value: 'objective-c' },
  { name: 'Objective-C++', value: 'objective-c++' },
  { name: 'Objective-J', value: 'objective-j' },
  { name: 'ObjectScript', value: 'objectscript' },
  { name: 'OCaml', value: 'ocaml' },
  { name: 'Odin', value: 'odin' },
  { name: 'Omgrofl', value: 'omgrofl' },
  { name: 'ooc', value: 'ooc' },
  { name: 'Opa', value: 'opa' },
  { name: 'Opal', value: 'opal' },
  { name: 'Open Policy Agent', value: 'open-policy-agent' },
  { name: 'OpenAPI Specification v2', value: 'openapi-specification-v2' },
  { name: 'OpenAPI Specification v3', value: 'openapi-specification-v3' },
  { name: 'OpenCL', value: 'opencl' },
  { name: 'OpenEdge ABL', value: 'openedge-abl' },
  { name: 'OpenQASM', value: 'openqasm' },
  { name: 'OpenRC runscript', value: 'openrc-runscript' },
  { name: 'OpenSCAD', value: 'openscad' },
  { name: 'OpenStep Property List', value: 'openstep-property-list' },
  { name: 'OpenType Feature File', value: 'opentype-feature-file' },
  { name: 'Option List', value: 'option-list' },
  { name: 'Org', value: 'org' },
  { name: 'Ox', value: 'ox' },
  { name: 'Oxygene', value: 'oxygene' },
  { name: 'Oz', value: 'oz' },
  { name: 'P4', value: 'p4' },
  { name: 'Pact', value: 'pact' },
  { name: 'Pan', value: 'pan' },
  { name: 'Papyrus', value: 'papyrus' },
  { name: 'Parrot', value: 'parrot' },
  { name: 'Parrot Assembly', value: 'parrot-assembly' },
  {
    name: 'Parrot Internal Representation',
    value: 'parrot-internal-representation',
  },
  { name: 'Pascal', value: 'pascal' },
  { name: 'Pawn', value: 'pawn' },
  { name: 'PDDL', value: 'pddl' },
  { name: 'PEG.js', value: 'peg.js' },
  { name: 'Pep8', value: 'pep8' },
  { name: 'Perl', value: 'perl' },
  { name: 'PHP', value: 'php' },
  { name: 'Pic', value: 'pic' },
  { name: 'Pickle', value: 'pickle' },
  { name: 'PicoLisp', value: 'picolisp' },
  { name: 'PigLatin', value: 'piglatin' },
  { name: 'Pike', value: 'pike' },
  { name: 'Pip Requirements', value: 'pip-requirements' },
  { name: 'Pkl', value: 'pkl' },
  { name: 'PlantUML', value: 'plantuml' },
  { name: 'PLpgSQL', value: 'plpgsql' },
  { name: 'PLSQL', value: 'plsql' },
  { name: 'Pod', value: 'pod' },
  { name: 'Pod 6', value: 'pod-6' },
  { name: 'PogoScript', value: 'pogoscript' },
  { name: 'Polar', value: 'polar' },
  { name: 'Pony', value: 'pony' },
  { name: 'Portugol', value: 'portugol' },
  { name: 'PostCSS', value: 'postcss' },
  { name: 'PostScript', value: 'postscript' },
  { name: 'POV-Ray SDL', value: 'pov-ray-sdl' },
  { name: 'PowerBuilder', value: 'powerbuilder' },
  { name: 'PowerShell', value: 'powershell' },
  { name: 'Praat', value: 'praat' },
  { name: 'Prisma', value: 'prisma' },
  { name: 'Processing', value: 'processing' },
  { name: 'Procfile', value: 'procfile' },
  { name: 'Proguard', value: 'proguard' },
  { name: 'Prolog', value: 'prolog' },
  { name: 'Promela', value: 'promela' },
  { name: 'Propeller Spin', value: 'propeller-spin' },
  { name: 'Protocol Buffer', value: 'protocol-buffer' },
  { name: 'Protocol Buffer Text Format', value: 'protocol-buffer-text-format' },
  { name: 'Public Key', value: 'public-key' },
  { name: 'Pug', value: 'pug' },
  { name: 'Puppet', value: 'puppet' },
  { name: 'Pure Data', value: 'pure-data' },
  { name: 'PureBasic', value: 'purebasic' },
  { name: 'PureScript', value: 'purescript' },
  { name: 'Python', value: 'python' },
  { name: 'Python console', value: 'python-console' },
  { name: 'Python traceback', value: 'python-traceback' },
  { name: 'Pyret', value: 'pyret' },
  { name: 'q', value: 'q' },
  { name: 'Q#', value: 'q#' },
  { name: 'QMake', value: 'qmake' },
  { name: 'QML', value: 'qml' },
  { name: 'Qt Script', value: 'qt-script' },
  { name: 'Quake', value: 'quake' },
  { name: 'R', value: 'r' },
  { name: 'Racket', value: 'racket' },
  { name: 'Ragel', value: 'ragel' },
  { name: 'Raku', value: 'raku' },
  { name: 'RAML', value: 'raml' },
  { name: 'Rascal', value: 'rascal' },
  { name: 'Raw token data', value: 'raw-token-data' },
  { name: 'RBS', value: 'rbs' },
  { name: 'RDoc', value: 'rdoc' },
  { name: 'Readline Config', value: 'readline-config' },
  { name: 'REALbasic', value: 'realbasic' },
  { name: 'Reason', value: 'reason' },
  { name: 'ReasonLIGO', value: 'reasonligo' },
  { name: 'Rebol', value: 'rebol' },
  { name: 'Record Jar', value: 'record-jar' },
  { name: 'Red', value: 'red' },
  { name: 'Redcode', value: 'redcode' },
  { name: 'Redirect Rules', value: 'redirect-rules' },
  { name: 'Regular Expression', value: 'regular-expression' },
  { name: "Ren'Py", value: "ren'py" },
  { name: 'RenderScript', value: 'renderscript' },
  { name: 'ReScript', value: 'rescript' },
  { name: 'reStructuredText', value: 'restructuredtext' },
  { name: 'REXX', value: 'rexx' },
  { name: 'Rez', value: 'rez' },
  { name: 'Rich Text Format', value: 'rich-text-format' },
  { name: 'Ring', value: 'ring' },
  { name: 'Riot', value: 'riot' },
  { name: 'RMarkdown', value: 'rmarkdown' },
  { name: 'RobotFramework', value: 'robotframework' },
  { name: 'Roc', value: 'roc' },
  { name: 'Roff', value: 'roff' },
  { name: 'Roff Manpage', value: 'roff-manpage' },
  { name: 'RON', value: 'ron' },
  { name: 'Rouge', value: 'rouge' },
  { name: 'RouterOS Script', value: 'routeros-script' },
  { name: 'RPC', value: 'rpc' },
  { name: 'RPGLE', value: 'rpgle' },
  { name: 'RPM Spec', value: 'rpm-spec' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'RUNOFF', value: 'runoff' },
  { name: 'Rust', value: 'rust' },
  { name: 'Sage', value: 'sage' },
  { name: 'SaltStack', value: 'saltstack' },
  { name: 'SAS', value: 'sas' },
  { name: 'Sass', value: 'sass' },
  { name: 'Scala', value: 'scala' },
  { name: 'Scaml', value: 'scaml' },
  { name: 'Scenic', value: 'scenic' },
  { name: 'Scheme', value: 'scheme' },
  { name: 'Scilab', value: 'scilab' },
  { name: 'SCSS', value: 'scss' },
  { name: 'sed', value: 'sed' },
  { name: 'Self', value: 'self' },
  { name: 'SELinux Policy', value: 'selinux-policy' },
  { name: 'ShaderLab', value: 'shaderlab' },
  { name: 'Shell', value: 'shell' },
  { name: 'ShellCheck Config', value: 'shellcheck-config' },
  { name: 'ShellSession', value: 'shellsession' },
  { name: 'Shen', value: 'shen' },
  { name: 'Sieve', value: 'sieve' },
  { name: 'Simple File Verification', value: 'simple-file-verification' },
  { name: 'Singularity', value: 'singularity' },
  { name: 'Slash', value: 'slash' },
  { name: 'Slice', value: 'slice' },
  { name: 'Slim', value: 'slim' },
  { name: 'Slint', value: 'slint' },
  { name: 'Smali', value: 'smali' },
  { name: 'Smalltalk', value: 'smalltalk' },
  { name: 'Smarty', value: 'smarty' },
  { name: 'SmPL', value: 'smpl' },
  { name: 'SMT', value: 'smt' },
  { name: 'Smithy', value: 'smithy' },
  { name: 'Snakemake', value: 'snakemake' },
  { name: 'Solidity', value: 'solidity' },
  { name: 'Soong', value: 'soong' },
  { name: 'SourcePawn', value: 'sourcepawn' },
  { name: 'SPARQL', value: 'sparql' },
  { name: 'Spline Font Database', value: 'spline-font-database' },
  { name: 'SQF', value: 'sqf' },
  { name: 'SQL', value: 'sql' },
  { name: 'SQLPL', value: 'sqlpl' },
  { name: 'Squirrel', value: 'squirrel' },
  { name: 'SRecode Template', value: 'srecode-template' },
  { name: 'SSH Config', value: 'ssh-config' },
  { name: 'Stan', value: 'stan' },
  { name: 'Standard ML', value: 'standard-ml' },
  { name: 'Starlark', value: 'starlark' },
  { name: 'STAR', value: 'star' },
  { name: 'Stata', value: 'stata' },
  { name: 'STL', value: 'stl' },
  { name: 'STON', value: 'ston' },
  { name: 'StringTemplate', value: 'stringtemplate' },
  { name: 'Stylus', value: 'stylus' },
  { name: 'SubRip Text', value: 'subrip-text' },
  { name: 'SugarSS', value: 'sugarss' },
  { name: 'SuperCollider', value: 'supercollider' },
  { name: 'Svelte', value: 'svelte' },
  { name: 'SVG', value: 'svg' },
  { name: 'Sway', value: 'sway' },
  { name: 'Sweave', value: 'sweave' },
  { name: 'Swift', value: 'swift' },
  { name: 'SWIG', value: 'swig' },
  { name: 'SystemVerilog', value: 'systemverilog' },
  { name: 'Talon', value: 'talon' },
  { name: 'Tcl', value: 'tcl' },
  { name: 'Tcsh', value: 'tcsh' },
  { name: 'Tea', value: 'tea' },
  { name: 'templ', value: 'templ' },
  { name: 'Terra', value: 'terra' },
  { name: 'Terraform Template', value: 'terraform-template' },
  { name: 'TeX', value: 'tex' },
  { name: 'Texinfo', value: 'texinfo' },
  { name: 'Text', value: 'text' },
  { name: 'TextGrid', value: 'textgrid' },
  { name: 'TextMate Properties', value: 'textmate-properties' },
  { name: 'Textile', value: 'textile' },
  { name: 'Thrift', value: 'thrift' },
  { name: 'TI Program', value: 'ti-program' },
  { name: 'TL-Verilog', value: 'tl-verilog' },
  { name: 'TLA', value: 'tla' },
  { name: 'Toit', value: 'toit' },
  { name: 'TOML', value: 'toml' },
  { name: 'TSQL', value: 'tsql' },
  { name: 'TSV', value: 'tsv' },
  { name: 'TSX', value: 'tsx' },
  { name: 'Turing', value: 'turing' },
  { name: 'Turtle', value: 'turtle' },
  { name: 'Twig', value: 'twig' },
  { name: 'TXL', value: 'txl' },
  { name: 'Type Language', value: 'type-language' },
  { name: 'TypeScript', value: 'typescript' },
  { name: 'Typst', value: 'typst' },
  { name: 'Unified Parallel C', value: 'unified-parallel-c' },
  { name: 'Unity3D Asset', value: 'unity3d-asset' },
  { name: 'Unix Assembly', value: 'unix-assembly' },
  { name: 'Uno', value: 'uno' },
  { name: 'UnrealScript', value: 'unrealscript' },
  { name: 'UrWeb', value: 'urweb' },
  { name: 'V', value: 'v' },
  { name: 'Vala', value: 'vala' },
  { name: 'Valve Data Format', value: 'valve-data-format' },
  { name: 'VBA', value: 'vba' },
  { name: 'VBScript', value: 'vbscript' },
  { name: 'VCL', value: 'vcl' },
  { name: 'Velocity Template Language', value: 'velocity-template-language' },
  { name: 'Verilog', value: 'verilog' },
  { name: 'VHDL', value: 'vhdl' },
  { name: 'Vim Help File', value: 'vim-help-file' },
  { name: 'Vim Script', value: 'vim-script' },
  { name: 'Vim Snippet', value: 'vim-snippet' },
  { name: 'Visual Basic .NET', value: 'visual-basic-.net' },
  { name: 'Visual Basic 6.0', value: 'visual-basic-6.0' },
  { name: 'Volt', value: 'volt' },
  { name: 'Vue', value: 'vue' },
  { name: 'Vyper', value: 'vyper' },
  { name: 'WDL', value: 'wdl' },
  { name: 'Web Ontology Language', value: 'web-ontology-language' },
  { name: 'WebAssembly', value: 'webassembly' },
  { name: 'WebAssembly Interface Type', value: 'webassembly-interface-type' },
  { name: 'WebIDL', value: 'webidl' },
  { name: 'WebVTT', value: 'webvtt' },
  { name: 'Wget Config', value: 'wget-config' },
  { name: 'WGSL', value: 'wgsl' },
  { name: 'Whiley', value: 'whiley' },
  { name: 'Wikitext', value: 'wikitext' },
  { name: 'Win32 Message File', value: 'win32-message-file' },
  { name: 'Windows Registry Entries', value: 'windows-registry-entries' },
  { name: 'wisp', value: 'wisp' },
  { name: 'Witcher Script', value: 'witcher-script' },
  { name: 'Wollok', value: 'wollok' },
  {
    name: 'World of Warcraft Addon Data',
    value: 'world-of-warcraft-addon-data',
  },
  { name: 'Wren', value: 'wren' },
  { name: 'X BitMap', value: 'x-bitmap' },
  { name: 'X Font Directory Index', value: 'x-font-directory-index' },
  { name: 'X PixMap', value: 'x-pixmap' },
  { name: 'X10', value: 'x10' },
  { name: 'xBase', value: 'xbase' },
  { name: 'XC', value: 'xc' },
  { name: 'XCompose', value: 'xcompose' },
  { name: 'XML', value: 'xml' },
  { name: 'XML Property List', value: 'xml-property-list' },
  { name: 'Xojo', value: 'xojo' },
  { name: 'Xonsh', value: 'xonsh' },
  { name: 'XPages', value: 'xpages' },
  { name: 'XProc', value: 'xproc' },
  { name: 'XQuery', value: 'xquery' },
  { name: 'XS', value: 'xs' },
  { name: 'XSLT', value: 'xslt' },
  { name: 'Xtend', value: 'xtend' },
  { name: 'YAML', value: 'yaml' },
  { name: 'YANG', value: 'yang' },
  { name: 'YARA', value: 'yara' },
  { name: 'YASnippet', value: 'yasnippet' },
  { name: 'Yacc', value: 'yacc' },
  { name: 'Yul', value: 'yul' },
  { name: 'ZAP', value: 'zap' },
  { name: 'Zeek', value: 'zeek' },
  { name: 'ZenScript', value: 'zenscript' },
  { name: 'Zephir', value: 'zephir' },
  { name: 'WGSL', value: 'wgsl' },
  { name: 'Zig', value: 'zig' },
  { name: 'ZIL', value: 'zil' },
  { name: 'Zimpl', value: 'zimpl' },
  { name: 'crontab', value: 'crontab' },
  { name: 'cURL Config', value: 'curl-config' },
  { name: 'desktop', value: 'desktop' },
  { name: 'dircolors', value: 'dircolors' },
  { name: 'edn', value: 'edn' },
  { name: 'fish', value: 'fish' },
  { name: 'hoon', value: 'hoon' },
  { name: 'jq', value: 'jq' },
  { name: 'kvlang', value: 'kvlang' },
  { name: 'mcfunction', value: 'mcfunction' },
  { name: 'mupad', value: 'mupad' },
  { name: 'nanorc', value: 'nanorc' },
  { name: 'nesC', value: 'nesc' },
  { name: 'ooc', value: 'ooc' },
  { name: 'q', value: 'q' },
  { name: 'reStructuredText', value: 'restructuredtext' },
  { name: 'robots.txt', value: 'robots.txt' },
  { name: 'sed', value: 'sed' },
  { name: 'templ', value: 'templ' },
  { name: 'wisp', value: 'wisp' },
  { name: 'xBase', value: 'xbase' },
];
