server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css

pages:
  - name: Home 
    columns:
      - size: small
        widgets:
          - type: search
            autofocus: true
            search-engine: google
            new-tab: true
            placeholder: Search...
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
              - title: Github
                shortcut: "!gh"
                url: https://github.com/search?q={QUERY}&type=repositories
          
          - type: calendar
            first-day-of-week: monday
          
          - type: weather
            location: Ho Chi Minh City, Vietnam
            units: metric
            hour-format: 24h
            hide-location: false

      - size: full
        widgets:
          - type: videos
            channels:
              - UCUuXPlozzyzcC0PHjLh6YaA # Duy Thanh Nguyen
              - UCRsd_L7wBGdHLhfacuy3QVw # Spiderum
              - UCQ0jSGgYMLmRMeTE6UaPPXg # duyluandethuong
              - UCY1kMZp36IQSyNx_9h4mpCg # mark ...
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCky92hx0lZxVBi2BJ6Zm2Hg # Tips Javascript
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
              - UCyqxvGyF5LO67HI6vdE5bfQ # Vinh Xo
          
          - type: group
            widgets:
              - type: iframe
                source: https://glance-iframe.khangng2100.live/trending
                title: github trending
                height: 410
              - type: reddit
                subreddit: technology
                show-thumbnails: true
                limit: 10
                collapse-after: 5
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true
                limit: 10
                collapse-after: 5
              - type: reddit
                subreddit: vozforums
                show-thumbnails: true
                limit: 10
                collapse-after: 5

      - size: small
        widgets:
          - type: markets
            # The link to go to when clicking on the symbol in the UI,
            # {SYMBOL} will be substituded with the symbol for each market
            symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/?timeframe=1M
            sort-by: change
            markets:
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: FPT.VN
                name: FPT Corporation 
              - symbol: HPG.VN
                name: Hoa Phat Group JSC
              - symbol: LTC-USD
                name: Litecoin
              - symbol: BTC
                name: Bitcoin
          
          - type: iframe
            source: https://glance-iframe.khangng2100.live/gold-price
            title: Giá vàng Việt Nam
            height: 350
  
  - name: System Dashboard
    columns:
      - size: small
        widgets:
          - type: dns-stats
            service: pihole
            url: http://192.168.1.76
            token: ${PIHOLE_TOKEN}
          
          - type: custom-api
            title: Cloudflared Tunnels
            css-class: "widget-type-cloudflared"
            cache: 4h
            url: https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/cfd_tunnel/${CLOUDFLARE_TUNNEL_ID}/configurations
            headers:
              Authorization: Bearer ${CLOUDFLARE_TUNNEL_TOKEN}
            template: |
              {{ $domain_name := ".example.com" }}  {{/* Set your domain name */}}

              <style>
                .widget-type-cloudflared li {
                  margin-top: var(--list-half-gap); 
                  border-top: 1px solid var(--color-separator);
                  padding-top: var(--list-half-gap);
                }
              </style>
              <ul class="dynamic-columns list-gap-15 list-with-separator">
              {{ range .JSON.Array "result.config.ingress" }}
                {{ if (.String "hostname") }}
                <li class="flex items-center gap-20">
                    <div class="shrink-0">
                        <img class="docker-container-icon" src="https://developers.cloudflare.com/logo.svg" alt="" loading="lazy">
                    </div>
                    <div class="min-width-0 grow">
                      <a href='https://{{ .String "hostname" }}' class="color-highlight size-title-dynamic block text-truncate" target="_blank" rel="noreferrer">{{ .String "hostname" | trimSuffix $domain_name }}</a>
                      {{ if (.String "service") }}
                      <div class="flex items-center gap-10" style="margin-bottom: 5px">
                        <div class="text-left">
                          <img src="/assets/img/link-down-right.png" style="width: auto; height: 20px; margin-left: 0px; margin-top: -4px;">
                        </div>
                        <div class="size-h6 flex-1 text-left">
                          <a href='{{ .String "service" | replaceAll "localhost" "192.168.0.150" }}' target="_blank" rel="noreferrer">{{ .String "service" }}</a>
                        </div>
                      </div>
                      {{ end}}
                    </div>
                </li>
                {{ end }}
              {{ end }}
              </ul>

      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: Media Services
            sites:
              - title: Plex
                url: http://192.168.1.76:32400
                check-url: http://192.168.1.76:32400
                icon: di:plex
              - title: NZBGet
                url: http://192.168.1.76:6789
                check-url: http://192.168.1.76:6789
                icon: di:nzbget

              - title: Radarr (Movies)
                url: http://192.168.1.76:7878
                check-url: http://192.168.1.76:7878
                icon: di:radarr

              - title: Sonarr (TV series)
                url: http://192.168.1.76:8989
                check-url: http://192.168.1.76:8989
                icon: di:sonarr

              - title: Qbittorrent
                url: http://192.168.1.76:8091
                check-url: http://192.168.1.76:8091
                icon: di:qbittorrent

              - title: Bazarr (Subtitles)
                url: http://192.168.1.76:6767
                check-url: http://192.168.1.76:6767
                icon: di:bazarr

          - type: monitor
            cache: 1m
            title: Network Services
            sites:
              - title: Pi-Hole
                url: http://192.168.1.76/admin
                check-url: http://192.168.1.76/admin
                icon: di:pi-hole

              - title: Cloudflare DDNS
                url: https://dash.cloudflare.com/44eac9f2adf39930db03120885adbb80/khangng2100.live
                check-url: http://192.168.1.76:8000
                icon: di:cloudflare

              - title: Cloudflare Tunnels
                url: https://one.dash.cloudflare.com/44eac9f2adf39930db03120885adbb80/networks/tunnels/cfd_tunnel/a871d8a9-57e3-4f65-be32-71202cbe8668/edit?tab=publicHostname
                check-url: http://192.168.1.76:8000
                icon: di:cloudflare

          - type: monitor
            cache: 1m
            title: Smart Home
            sites:
              - title: Homebridge
                url: http://192.168.1.76:8581
                check-url: http://192.168.1.76:8581
                icon: di:homebridge

          - type: docker-containers
            title: Docker Containers Status
            show-stopped: true
            show-logs: true
            refresh: 30s
            services:
              jellyfin:
                image: lscr.io/linuxserver/jellyfin:latest
                labels:
                  glance.name: Jellyfin
                  glance.icon: si:jellyfin
                  glance.url: http://192.168.1.76:8096
                  glance.description: Movies & shows

              jellyseerr:
                image: fallenbagel/jellyseerr:latest
                labels:
                  glance.name: Jellyseerr
                  glance.icon: si:search
                  glance.url: http://192.168.1.76:5055
                  glance.description: Media request manager

              tautulli:
                image: lscr.io/linuxserver/tautulli:latest
                labels:
                  glance.name: Tautulli
                  glance.icon: si:plex
                  glance.url: http://192.168.1.76:8181
                  glance.description: Plex usage stats

              overseerr:
                image: lscr.io/linuxserver/overseerr:latest
                labels:
                  glance.name: Overseerr
                  glance.icon: si:overleaf
                  glance.url: http://192.168.1.76:5055
                  glance.description: Request & approve movies

              prowlarr:
                image: lscr.io/linuxserver/prowlarr:latest
                labels:
                  glance.name: Prowlarr
                  glance.icon: si:rss
                  glance.url: http://192.168.1.76:9696
                  glance.description: Indexer manager

              radarr:
                image: lscr.io/linuxserver/radarr:latest
                labels:
                  glance.name: Radarr
                  glance.icon: si:film
                  glance.url: http://192.168.1.76:7878
                  glance.description: Movie downloader

              sonarr:
                image: lscr.io/linuxserver/sonarr:latest
                labels:
                  glance.name: Sonarr
                  glance.icon: si:television
                  glance.url: http://192.168.1.76:8989
                  glance.description: TV show downloader

              qbittorrent:
                image: lscr.io/linuxserver/qbittorrent:latest
                labels:
                  glance.name: qBittorrent
                  glance.icon: si:qbittorrent
                  glance.url: http://192.168.1.76:8091
                  glance.description: Torrent client

              cloudflare-ddns:
                image: favonia/cloudflare-ddns:latest
                labels:
                  glance.name: Cloudflare DDNS
                  glance.icon: si:cloudflare
                  glance.url: http://192.168.1.76:8000
                  glance.description: Dynamic DNS Updater

              pihole:
                image: pihole/pihole:2024.07.0
                labels:
                  glance.name: Pi-hole
                  glance.icon: si:pihole
                  glance.url: http://192.168.1.76/admin
                  glance.description: Network-wide ad blocker
      - size: small
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: Pi5
          - type: monitor
            cache: 1m
            title: System Monitoring
            sites:
              - title: Grafana
                url: http://192.168.1.76:3000
                check-url: http://192.168.1.76:3000
                icon: di:grafana
              - title: Prometheus
                url: http://192.168.1.76:9090
                check-url: http://192.168.1.76:9090
                icon: di:prometheus
              - title: InfluxDB
                url: http://192.168.1.76:8086
                check-url: http://192.168.1.76:8086
                icon: di:influxdb
      