server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css

pages:
  - name: Startpage
    width: slim
    hide-desktop-navigation: false
    center-vertically: true
    columns:
      - size: small
        widgets:
          - type: dns-stats
            service: pihole
            url: http://192.168.1.76
            token: ${PIHOLE_TOKEN}

          - type: monitor
            cache: 1m
            title: System Monitoring
            sites:
              - title: Grafana
                url: http://192.168.1.76:3000
                check-url: http://192.168.1.76:3000
                icon: di:grafana
              - title: Prometheus
                url: http://192.168.1.76:9090
                check-url: http://192.168.1.76:9090
                icon: di:prometheus
              - title: InfluxDB
                url: http://192.168.1.76:8086
                check-url: http://192.168.1.76:8086
                icon: di:influxdb

      - size: full
        widgets:
          - type: search
            autofocus: true
            search-engine: google
            new-tab: true
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}
              - title: Github
                shortcut: "!gh"
                url: https://github.com/search?q={QUERY}&type=repositories

          - type: monitor
            cache: 1m
            title: Media Services
            sites:
              - title: Qbittorrent
                url: http://192.168.1.76:8091
                check-url: http://192.168.1.76:8091
                icon: di:qbittorrent
              - title: NZBGet
                url: http://192.168.1.76:6789
                check-url: http://192.168.1.76:6789
                icon: di:nzbget
              - title: Prowlarr
                url: http://192.168.1.76:9696
                check-url: http://192.168.1.76:9696
                icon: di:prowlarr

          - type: monitor
            cache: 1m
            title: Network Services
            sites:
              - title: Pi-Hole
                url: http://192.168.1.76/admin
                check-url: http://192.168.1.76/admin
                icon: di:pi-hole
              - title: Cloudflare DDNS
                url: https://dash.cloudflare.com
                check-url: http://192.168.1.76:8000
                icon: di:cloudflare

          - type: monitor
            cache: 1m
            title: Smart Home
            sites:
              - title: Homebridge
                url: http://192.168.1.76:8581
                check-url: http://192.168.1.76:8581
                icon: di:homebridge

  - name: Home
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    # hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://omgubuntu.co.uk/feed
                title: OmgUbuntu
                limit: 4
              - url: https://9to5linux.com/feed/atom
                title: 9to5Linux
                limit: 4

          - type: twitch-channels
            channels:
              - technotim
              - piratesoftware

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee

          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true

      - size: small
        widgets:
          - type: weather
            location: 98664
            units: imperial
            hour-format: 12h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true

          - type: markets
            # The link to go to when clicking on the symbol in the UI,
            # {SYMBOL} will be substituded with the symbol for each market
            symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
            markets:
              - symbol: LTC-USD
                name: Litecoin
              - symbol: XRP-USD
                name: Ripple
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft

          - type: monitor
            cache: 1m
            title: Smart Home Control
            sites:
              - title: Homebridge
                url: http://192.168.1.76:8581
                check-url: http://192.168.1.76:8581
                icon: di:homebridge

  - name: Default
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

          - type: twitch-channels
            channels:
              - theprimeagen
              - j_blow
              - piratesoftware
              - cohhcarnage
              - christitustech
              - EJ_SA

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true

      - size: small
        widgets:
          - type: weather
            location: London, United Kingdom
            units: metric # alternatively "imperial"
            hour-format: 12h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft

          - type: releases
            cache: 1d
            # Without authentication the Github API allows for up to 60 requests per hour. You can create a
            # read-only token from your Github account settings and use it here to increase the limit.
            # token: ...
            repositories:
              - glanceapp/glance
              - go-gitea/gitea
              - immich-app/immich
              - syncthing/syncthing
